# Kubernetes version: 1.27+
# This file contains Secret resources for storing sensitive configuration data
# All secret values should be base64 encoded before being added to this file
# Uses AWS KMS for encryption at rest

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: provocative-cloud
  labels:
    app: backend-api
    component: secrets
    managed-by: provocative-cloud
  annotations:
    rotation-schedule: "30d"
    last-rotated: "timestamp"
    encryption.kubernetes.io/provider: "aws-kms"
type: Opaque
data:
  JWT_SECRET_KEY: "<base64_encoded_jwt_secret>"
  JWT_REFRESH_SECRET: "<base64_encoded_jwt_refresh_secret>"
  GOOGLE_CLIENT_ID: "<base64_encoded_google_client_id>"
  GOOGLE_CLIENT_SECRET: "<base64_encoded_google_client_secret>"
  STRIPE_API_KEY: "<base64_encoded_stripe_api_key>"
  STRIPE_WEBHOOK_SECRET: "<base64_encoded_stripe_webhook_secret>"
  DATABASE_URL: "<base64_encoded_database_url>"
  DATABASE_PASSWORD: "<base64_encoded_database_password>"
  REDIS_URL: "<base64_encoded_redis_url>"
  REDIS_PASSWORD: "<base64_encoded_redis_password>"
  AWS_ACCESS_KEY_ID: "<base64_encoded_aws_access_key>"
  AWS_SECRET_ACCESS_KEY: "<base64_encoded_aws_secret_key>"
  AWS_REGION: "<base64_encoded_aws_region>"
  S3_BUCKET: "<base64_encoded_s3_bucket>"

---
apiVersion: v1
kind: Secret
metadata:
  name: gpu-manager-secrets
  namespace: provocative-cloud
  labels:
    app: gpu-manager
    component: secrets
    managed-by: provocative-cloud
  annotations:
    rotation-schedule: "90d"
    last-rotated: "timestamp"
    encryption.kubernetes.io/provider: "aws-kms"
type: Opaque
data:
  NVIDIA_LICENSE_KEY: "<base64_encoded_nvidia_license>"
  NVIDIA_GRID_LICENSE: "<base64_encoded_nvidia_grid_license>"
  MONITORING_API_KEY: "<base64_encoded_monitoring_key>"
  METRICS_ENDPOINT: "<base64_encoded_metrics_endpoint>"
  GPU_MANAGER_API_KEY: "<base64_encoded_gpu_manager_key>"

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: provocative-cloud
  labels:
    app: monitoring
    component: secrets
    managed-by: provocative-cloud
  annotations:
    rotation-schedule: "60d"
    last-rotated: "timestamp"
    encryption.kubernetes.io/provider: "aws-kms"
type: Opaque
data:
  GRAFANA_ADMIN_PASSWORD: "<base64_encoded_grafana_password>"
  GRAFANA_SECRET_KEY: "<base64_encoded_grafana_secret>"
  ALERTMANAGER_SLACK_URL: "<base64_encoded_slack_webhook>"
  ALERTMANAGER_EMAIL_PASSWORD: "<base64_encoded_email_password>"
  PROMETHEUS_ADMIN_PASSWORD: "<base64_encoded_prometheus_password>"
  PROMETHEUS_REMOTE_WRITE_URL: "<base64_encoded_remote_write_url>"
  PROMETHEUS_REMOTE_WRITE_TOKEN: "<base64_encoded_remote_write_token>"