# Kubernetes version: 1.27+
# Storage classes for Provocative Cloud platform using Ceph backend
# Implements tiered storage solutions for different performance requirements

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
provisioner: kubernetes.io/ceph
parameters:
  type: gp3
  fsType: ext4
  iopsPerGB: "3000"
  throughput: "125"
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: ceph-secret
  csi.storage.k8s.io/provisioner-secret-namespace: provocative-cloud
  csi.storage.k8s.io/node-stage-secret-name: ceph-secret
  csi.storage.k8s.io/node-stage-secret-namespace: provocative-cloud
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - noatime
  - nodiratime

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gpu-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
provisioner: kubernetes.io/ceph
parameters:
  type: io2
  fsType: ext4
  iopsPerGB: "10000"
  throughput: "500"
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: ceph-secret
  csi.storage.k8s.io/provisioner-secret-namespace: provocative-cloud
  csi.storage.k8s.io/node-stage-secret-name: ceph-secret
  csi.storage.k8s.io/node-stage-secret-namespace: provocative-cloud
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - noatime
  - nodiratime
  - discard